### ISSUE TITLE
A problem about pointnet_cls model loading

### ISSUE THREAD

**Issue by zjhJOJO** [RyanHangZhou/LG-GAN#4]
Thank you for your excellent work and open source code. 
My deep learning environment : Ubuntu 20.04, CUDA 11.4, and tensorflow 2.6. 
I downloaded the pointnet_cls model that you provided in Google drive and put it to the directory "checkpoints/pointnet", but something error occurred, namely, 
============================================================
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Key conv1/biases not found in checkpoint
         [[node save/RestoreV2 (defined at lggan.py:201) ]]
  (1) Not found: Key conv1/biases not found in checkpoint
         [[node save/RestoreV2 (defined at lggan.py:201) ]]
         [[save/RestoreV2/_15]]
0 successful operations.
0 derived errors ignored.
============================================================
when i ran the command "python -u lggan.py --adv_path LGGAN --checkpoints_path LGGAN --log_path LGGAN --tau 1e2".
I am sure that i do not modify any file related to your provided model files, i.e., 
=============================================================
checkpoint
model.cpkt-202080.data-00000-of-00001
model.cpkt-202080.index
model.cpkt-202080.meta
=============================================================
I will greatly appreciate if you could offer me some advises. Thank you :D

**Comment by RyanHangZhou** [comment]
Hi,

I think it may be the incompatibility of the environment version with my
code. Please follow the same environment setup as mine.

Cheers
Hang

**Comment by zjhJOJO** [comment]
Thank you for your reply. I have solved this problem by retraining the attacked model "pointnet_cls"
